/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mentalhealth.view;

import com.mycompany.mentalhealth.controller.PatientCntl;
import com.mycompany.mentalhealth.model.Patient;
import java.util.ArrayList;

/**
 *
 * @author emreb
 */
public class PatientUIDetail extends javax.swing.JFrame {
    
    private PatientCntl patientCntl;
    private ArrayList<Patient> listOfPatients;
    private int currentPatient = 0;

    public int getCurrentPatient() {
        return currentPatient;
    }

    public void setCurrentPatient(int currentPatient) {
        this.currentPatient = currentPatient;
    }
    private Patient patient;

    public ArrayList<Patient> getPatientList(){
        return listOfPatients;
    
    }
    /**
     * Creates new form PatientUI
     */
    public PatientUIDetail(PatientCntl patientCntl) {
        this.patientCntl = patientCntl;
        initComponents();
        listOfPatients = patientCntl.getListOfPatients();
        
        if(listOfPatients.size() == 0){
            defaultPatient();
        
        }else {
            patient = listOfPatients.get(currentPatient);
            parsePatient(patient);
        
        }
       
        
        
         btnQuit.addActionListener(e -> {
        // Call writePatientListFile() on the PatientList before exiting
        patientCntl.getPatientList().writePatientListFile();
        // Exit the application
        System.exit(0);
    });
    }
    
    
    public PatientUIDetail(PatientCntl patientCntl, Patient patient) {
        initComponents();
        this.patientCntl = patientCntl;
        this.patient = patient;
        listOfPatients = patientCntl.getListOfPatients();
        patient = listOfPatients.get(currentPatient);
        parsePatient(patient);
        
         btnQuit.addActionListener(e -> {
        // Call writePatientListFile() on the PatientList before exiting
        patientCntl.getPatientList().setListOfPatients(listOfPatients);
        System.out.println(listOfPatients);
        patientCntl.getPatientList().writePatientListFile();
        // Exit the application
        System.exit(0);
    });
    }
    
    public void parsePatient(Patient patient){
        inptPatientCondition.setText(patient.getHealthCondition());
        inptFirstName.setText(patient.getFirstName());
        inptLastName.setText(patient.getLastName());
        inptGender.setText(patient.getGender());
        inptPhoneNumber.setText(Long.toString(patient.getPhoneNumber()));
        inptAssignedProfessional.setText(patient.getAssignedProfessional());
        inptDateOfBirth.setText(patient.getDateOfBirth());
        inptAddress.setText(patient.getAddress());
        inptPatientID.setText(String.valueOf(patient.getPatientId()));
    }
    
    public void defaultPatient (){
        inptPatientCondition.setText("depresssion");
        inptFirstName.setText("emptyfirstname");
        inptLastName.setText("emptylastname");
        inptGender.setText("emptygender");
        inptPhoneNumber.setText("1111111111");
        inptAssignedProfessional.setText("emptyprof");
        inptDateOfBirth.setText("1/1/1111");
        inptAddress.setText("emptyaddress");
        inptPatientID.setText("111111");
        
    
    
    }
    public String getPatientCondition(){
        return inptPatientCondition.getText();
    }
    public String getFirstName(){
        return inptFirstName.getText();
    }
    public String getLastName(){
        return inptLastName.getText();
    }
    public String getGender(){
        return inptGender.getText();
    }
    public String getPhoneNumber(){
        return inptPhoneNumber.getText();
    }
    public String getAssignedProfessional(){
        return inptAssignedProfessional.getText();
    }
    public String getDateOfBirth(){
        return inptDateOfBirth.getText();
    }
    public String getAddress(){
        return inptAddress.getText();
    }
     public String getPatientID(){
        return inptPatientID.getText();
    }

//    String firstName, String lastName, String gender, long phoneNumber, String assignedProfessional, String dateOfBirth, String address, String healthCondition, int patientId
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        lblPatientCondition = new javax.swing.JLabel();
        inptPatientCondition = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblAssignedProf = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        inptFirstName = new javax.swing.JTextField();
        inptLastName = new javax.swing.JTextField();
        inptGender = new javax.swing.JTextField();
        inptPhoneNumber = new javax.swing.JTextField();
        inptAssignedProfessional = new javax.swing.JTextField();
        inptDateOfBirth = new javax.swing.JTextField();
        inptAddress = new javax.swing.JTextField();
        inptPatientID = new javax.swing.JTextField();
        btnBacktoList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        header.setText("Mental Health Patients");

        lblPatientCondition.setText("Patient Condition");

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNext.setText("Next");

        btnPrevious.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrevious.setText("Previous");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add");

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Delete");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update");

        btnQuit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuit.setText("Quit");

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblGender.setText("Gender");

        lblPhoneNumber.setText("Phone Number");

        lblAssignedProf.setText("Assigned Professional");

        lblDateOfBirth.setText("Date Of Birth");

        lblAddress.setText("Address");

        lblPatientID.setText("Patient ID");

        btnBacktoList.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBacktoList.setText("Back to List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblGender)
                                                    .addGap(96, 96, 96))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblLastName)
                                                    .addGap(79, 79, 79)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblFirstName)
                                                .addGap(77, 77, 77)))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(inptLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                            .addComponent(inptGender)
                                            .addComponent(inptFirstName)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAssignedProf)
                                            .addComponent(lblPhoneNumber)
                                            .addComponent(lblDateOfBirth)
                                            .addComponent(lblAddress)
                                            .addComponent(lblPatientID)
                                            .addComponent(lblPatientCondition))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(inptAssignedProfessional, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                            .addComponent(inptDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inptAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inptPatientID, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inptPatientCondition, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inptPhoneNumber)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBacktoList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header)
                .addGap(32, 32, 32)
                .addComponent(btnQuit))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(header)
                        .addComponent(btnBacktoList))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnQuit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(inptFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(inptLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(inptGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(inptPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignedProf)
                    .addComponent(inptAssignedProfessional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(inptDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(inptAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(inptPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientCondition)
                    .addComponent(inptPatientCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnBacktoList;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnNext;
    public javax.swing.JButton btnPrevious;
    public javax.swing.JButton btnQuit;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JLabel header;
    private javax.swing.JTextField inptAddress;
    private javax.swing.JTextField inptAssignedProfessional;
    private javax.swing.JTextField inptDateOfBirth;
    private javax.swing.JTextField inptFirstName;
    private javax.swing.JTextField inptGender;
    private javax.swing.JTextField inptLastName;
    private javax.swing.JTextField inptPatientCondition;
    private javax.swing.JTextField inptPatientID;
    private javax.swing.JTextField inptPhoneNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAssignedProf;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPatientCondition;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
